

DROP TABLE IF EXISTS BLOG_USER;  

CREATE TABLE BLOG_USER (  
id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  
name VARCHAR(50) NOT NULL,  
username VARCHAR(50) NOT NULL,
email VARCHAR(512) NOT NULL,
phone VARCHAR(50) NOT NULL,
website VARCHAR(512) NOT NULL,
createdBy int,
updatedBy int,
createdDateTime TIMESTAMP,
updatedDateTime TIMESTAMP
);  

DROP TABLE IF EXISTS ADDRESS; 
 
CREATE TABLE ADDRESS (  
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
userId INT,  
street VARCHAR(512) ,  
suite VARCHAR(100) ,
city VARCHAR(100) ,
zipcode VARCHAR(20) 
);  


DROP TABLE IF EXISTS GEO_LOCATION;  

CREATE TABLE GEO_LOCATION (  
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  
addressId INT , 
lat VARCHAR(50) NOT NULL,
lng VARCHAR(50) NOT NULL
);  



DROP TABLE IF EXISTS COMPANY;  

CREATE TABLE COMPANY (  
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  
userId INT, 
name VARCHAR(512) NOT NULL,  
catchPhrase VARCHAR(512) NOT NULL,
bs VARCHAR(512) NOT NULL
); 


DROP TABLE IF EXISTS BLOG_POST;  

CREATE TABLE BLOG_POST (  
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  
userId INT, 
title VARCHAR(512) NOT NULL,  
body VARCHAR(4000) NOT NULL,
actionedBy smallint default 0, 
updatedBy int,
createdDateTime TIMESTAMP,
updatedDateTime TIMESTAMP
); 


DROP TABLE IF EXISTS BLOG_AUDIT;  

CREATE TABLE BLOG_AUDIT(
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
blogPostId INT NOT NULL,
blogTitle VARCHAR(512) NOT NULL,  
blogBody VARCHAR(4000) NOT NULL,
createdBy int,
action smallint default 0, 
actionedTime TIMESTAMP);
 










